'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("PRA_PIS.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _108_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("108-blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1092648() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1092648", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _323_3233189_plm_migration_data_source_icon_png_clipart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("323-3233189_plm-migration-data-source-icon-png-clipart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _480px_No_image_available_svg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("480px-No_image_available.svg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to outline_insert_comment_black_24dp.
        '''</summary>
        Friend ReadOnly Property _String() As String
            Get
                Return ResourceManager.GetString("String", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property abc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_add_a_photo_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_add_a_photo_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_arrow_back_ios_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_arrow_back_ios_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_arrow_back_ios_white_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_arrow_back_ios_white_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_arrow_forward_ios_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_arrow_forward_ios_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_arrow_forward_ios_white_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_arrow_forward_ios_white_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_beenhere_white_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_beenhere_white_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_camera_alt_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_camera_alt_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_check_white_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_check_white_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_check_white_18dp1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_check_white_18dp1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_description_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_description_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_description_black_18dp1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_description_black_18dp1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_notifications_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_notifications_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_notifications_black_18dp1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_notifications_black_18dp1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_save_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_save_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_settings_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_settings_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_sync_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_sync_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property baseline_verified_white_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("baseline_verified_white_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property close_icon() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_icon", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property close_icon_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("close_icon_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Dark_Color_Wallpapers_030() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Dark-Color-Wallpapers-030", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property giphy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("giphy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_site_quality_warranty_36() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-site-quality-warranty-36", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property images() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("images", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property img000001() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("img000001", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property light_blue_gradient_by_sirmudkipz13_d6x2542_fullview() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("light_blue_gradient_by_sirmudkipz13_d6x2542-fullview", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Minimized_Left() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Minimized_Left", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Minimized_Left_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Minimized_Left_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NoRecordFound() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NoRecordFound", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_add_box_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_add_box_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_add_box_black_18dp1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_add_box_black_18dp1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_arrow_forward_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_arrow_forward_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_assignment_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_assignment_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_assignment_turned_in_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_assignment_turned_in_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_assignment_white_24dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_assignment_white_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_attachment_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_attachment_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_book_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_book_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_build_white_24dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_build_white_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_cancel_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_cancel_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_check_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_check_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_description_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_description_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_double_arrow_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_double_arrow_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_double_arrow_black_18dp___Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_double_arrow_black_18dp - Copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_double_arrow_black_18dp1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_double_arrow_black_18dp1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_edit_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_edit_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_edit_black_24dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_edit_black_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_event_note_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_event_note_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_folder_shared_white_24dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_folder_shared_white_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_group_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_group_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_home_work_white_24dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_home_work_white_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_insert_comment_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_insert_comment_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_insert_comment_black_24dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_insert_comment_black_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_insert_drive_file_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_insert_drive_file_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_list_alt_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_list_alt_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_local_offer_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_local_offer_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_local_shipping_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_local_shipping_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_low_priority_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_low_priority_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_my_location_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_my_location_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_note_add_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_note_add_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_notifications_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_notifications_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_person_add_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_person_add_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_playlist_add_check_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_playlist_add_check_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_post_add_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_post_add_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_post_add_black_24dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_post_add_black_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_print_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_print_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_refresh_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_refresh_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_save_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_save_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_scanner_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_scanner_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_search_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_search_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_search_black_24dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_search_black_24dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_settings_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_settings_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_subdirectory_arrow_right_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_subdirectory_arrow_right_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_transfer_within_a_station_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_transfer_within_a_station_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property outline_view_list_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outline_view_list_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PADLOCK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PADLOCK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PRA_LOGO_WHITE_BG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PRA LOGO WHITE BG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PRA_LOGO_WHITE_HALF_BG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PRA LOGO WHITE HALF BG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property REQ_FIELD() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("REQ_FIELD", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property round_done_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("round_done_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property round_done_outline_white_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("round_done_outline_white_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property round_folder_shared_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("round_folder_shared_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property round_vpn_key_black_18dp() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("round_vpn_key_black_18dp", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property round_vpn_key_black_18dp1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("round_vpn_key_black_18dp1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SCAN_DOCUMENT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCAN_DOCUMENT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to outline_insert_comment_black_24dp.
        '''</summary>
        Friend ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property updating() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("updating", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property updating1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("updating1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
