'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("VON, VAN, MARK AND GENO")>  _
        Public Property PRADEV() As String
            Get
                Return CType(Me("PRADEV"),String)
            End Get
            Set
                Me("PRADEV") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\192.168.1.8\Update Server\PIS PROGRAM\")>  _
        Public Property FILEPATH() As String
            Get
                Return CType(Me("FILEPATH"),String)
            End Get
            Set
                Me("FILEPATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\192.168.1.8\Update Server\RIMS PROGRAM\RIMSEXEBACKUP\RIMS.exe")>  _
        Public Property RIMSEXEBACKUPPATH() As String
            Get
                Return CType(Me("RIMSEXEBACKUPPATH"),String)
            End Get
            Set
                Me("RIMSEXEBACKUPPATH") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.8\SQLPRA1;Initial Catalog=PRAMASTERDATABASE;Persist Securit"& _ 
            "y Info=True;User ID=sa;Password=pr@@dm1n2017507"&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public ReadOnly Property PRAMasterDBConnString() As String
            Get
                Return CType(Me("PRAMasterDBConnString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("( V.01-2019 )"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"PROCUREMENT INFORMATION SYSTEM (PIS)")>  _
        Public Property APPVER() As String
            Get
                Return CType(Me("APPVER"),String)
            End Get
            Set
                Me("APPVER") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.8\SQLPRA1;Initial Catalog=PRA_PROPERTYDB;Persist Security I"& _ 
            "nfo=True;User ID=sa;Password=pr@@dm1n2017507")>  _
        Public ReadOnly Property PRA_PROPERTYDBConnectionString() As String
            Get
                Return CType(Me("PRA_PROPERTYDBConnectionString"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("\\192.168.1.8\PRA Programs\PIS SCANNED FILES\")>  _
        Public Property PIS_DIR() As String
            Get
                Return CType(Me("PIS_DIR"),String)
            End Get
            Set
                Me("PIS_DIR") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.8\SQLPRA1;Initial Catalog=PRA_BMSDB;Persist Security Info=T"& _ 
            "rue;User ID=sa;Password=pr@@dm1n2017507"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10))>  _
        Public Property PRA_BMSDBConnectionString() As String
            Get
                Return CType(Me("PRA_BMSDBConnectionString"),String)
            End Get
            Set
                Me("PRA_BMSDBConnectionString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("TOR (PIS) - PR")>  _
        Public Property PIS_FILENAME_PR() As String
            Get
                Return CType(Me("PIS_FILENAME_PR"),String)
            End Get
            Set
                Me("PIS_FILENAME_PR") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.PRA_PIS.My.MySettings
            Get
                Return Global.PRA_PIS.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
